### ISSUE TITLE
Automatische metadata object voor rooms

### ISSUE THREAD

**Issue by Laurens256** [svennijhuis/Blok-Tech-GamingBuddy#2]
De metadata objects voor rooms in de collection "filters" worden nu nog handmatig aangemaakt. Hier moet een function voor worden gemaakt die kijkt of er al een metadata object voor de kamer bestaat zodra deze wordt gejoined. Als deze nog niet bestaat moet hij automatisch worden aangemaak
<img width="726" alt="Screenshot 2022-03-22 162406" src="https://user-images.githubusercontent.com/85798751/159517552-4c8eac08-ddb1-4a22-8623-5e6755465b60.png">

**Comment by ArisRosbach** [comment]
Deze functie:
`const createRoomInfo = async (roomName) => {`
In het bestand utils/filters/roomInfo.js kan wat meer comments bevatten. Een buitenstaander moet begrijpen wat er in deze functie gebeurd.
Maar de rest van deze code ziet er echt top uit!

**Comment by Laurens256** [comment]
> Deze functie: `const createRoomInfo = async (roomName) => {` In het bestand utils/filters/roomInfo.js kan wat meer comments bevatten. Een buitenstaander moet begrijpen wat er in deze functie gebeurd. Maar de rest van deze code ziet er echt top uit!

Comment toegevoegd
