### ISSUE TITLE
Room data

### ISSUE THREAD

**Issue by ArisRosbach** [svennijhuis/Blok-Tech-GamingBuddy#7]
Ik ben nu bezig met dat je groepsinformatie kan zien van de chat

**Comment by ArisRosbach** [comment]
Data van de room weergeven is gelukt:
![image](https://user-images.githubusercontent.com/94171125/160400051-9af45349-b82f-4a6e-a862-f3d28044f069.png)
Je ziet nu de naam, een omschrijving, de genres en de gesproken talen.

**Comment by Laurens256** [comment]
lgtm
